---
- name: webserver
  hosts: ubuntuservers
  become: true
  tasks:
  - name: install apache2
    apt: name=apache2 update_cache=yes state=latest

  - name: index.html
    copy:
      content: "<h1>Happy Holidays!!!</h1>"
      dest: /var/www/html/index.html

  - name: restart apache2
    service:
      name: apache2
      state: restarted
      enabled: yes
